config/routes.rb
TVillion::Application.routes.draw do
  get "jobs/index"
  get "jobs/get_tvinfo"
  get "jobs/schedule_next_download"
  get "jobs/update_download_status"

  resources :shows do
    collection do
      get 'search'
    end
    get 'downloads', on: :member
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/download.rb
require 'tvillion/transmission'

class Download < ActiveRecord::Base
  include Comparable

  attr_accessible :show_id, :season, :episode, :download_id, :status, :progress

  validates :show_id, :season, :episode, :download_id, :status, :presence => true


  # compare based on status
  def <=>(other)
    status <=> other.status
  end

  def done?
    status == TVillion::Transmission::StatusCode::DONE
  end

  def progressPercent
    if progress.nil?
      0
    else
      progress * 100
    end
  end

  def statusName
    TVillion::Transmission::StatusCode::get_name_from_transmission_status(status)
  end
end

app/models/show.rb
class Show < ActiveRecord::Base
  include Comparable

  attr_accessor :current_download

  attr_accessible :name, :season, :episode, :tvrage_id, :runtime, :hd, :image_url, :last_show_date, :last_season, :last_episode, :next_show_date, :next_season, :next_episode, :search_name

  validates :name, :presence => true

  def generate_search_string()
    return "#{generate_name_string()} #{generate_hd_string()} #{generate_episode_string()}"
  end

  def generate_name_string()
    if search_name.nil? or search_name.blank?
      return name
    else
      return search_name
    end
  end

  def generate_hd_string()
    if hd
      return "720p"
    else
      return ""
    end
  end

  def generate_episode_string()
    return "S%02dE%02d" % [season, episode]
  end
  
  def future_download?()
    return false if season.nil? or episode.nil? or last_season.nil? or last_episode.nil?
    return (season==last_season and episode<=last_episode)
  end
  
  # compare based on next_show_date
  def <=>(other)
    return 0 if !next_show_date && !other.next_show_date
    return 1 if !next_show_date
    return -1 if !other.next_show_date
    next_show_date <=> other.next_show_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
require 'tvillion/transmission'
require 'tvillion/torrentsearch'
require 'tvillion/tvinfo'

class JobsController < ApplicationController
  include TVillion::TvInfo
  include TVillion::TorrentSearch
  
  def get_tvinfo
    @shows = Show.all
    @shows.each do |show|
      generate_show(show)
      puts show.inspect
      show.update_attributes(params[:show])
    end
    generate_response()
  end
  
  def schedule_next_download
    @transmission_client = TVillion::Transmission::Client.new('localhost', '9091')
    @shows = Show.all
    @shows.each do |show|
      if show.season.nil? or show.episode.nil?
        puts "skipping #{show.name}, no episodes to download"
        next
      end
      if show.season != show.last_season
        puts "cannot download episodes for #{show.name}, download from a different season not supported"
        next
      end
      if show.episode > show.last_episode
        puts "cannot download episodes for #{show.name}, episode not yet aired"
        next
      end
      
      torrent_url = get_search_results(show.generate_search_string())
      unless torrent_url.nil?
        begin
          @id = @transmission_client.add_torrent(torrent_url)
          @download = Download.new(show_id: show.id, season: show.season, episode: show.episode, download_id: @id, status: TVillion::Transmission::StatusCode::UNKNOWN)
          @download.save
          puts @download.inspect
          get_next_episode(show)
          puts show.inspect
          show.update_attributes(params[:show])
        rescue Exception => e
          puts "error downloading show #{show.name}: " + e.message
        end
      else
        puts "cannot download episodes for #{show.name}, no torrents found"
      end
    end
    generate_response()
  end

  def update_download_status
    @transmission_client = TVillion::Transmission::Client.new('localhost', '9091')
    @downloads = Download.where(status != TVillion::Transmission::StatusCode::DONE)
    @downloads.each do |download|
      unless download.done? 
        @status_response = @transmission_client.check_torrent(download.download_id)
        download.status = @status_response.status
        download.progress = @status_response.percentDone
        download.update_attributes(params[:download])
      end
    end
    generate_response()
  end
  
  private
  def generate_response
    @status = Status.new()
    @status.result = "success"
    respond_to do |format|
      format.html
      format.xml  { render :xml => @status }
      format.json { render :json => @status }
    end
  end
  
  class Status
    attr_accessor :result
  end
end

app/controllers/shows_controller.rb
require 'tvillion/tvinfo'

class ShowsController < ApplicationController
  include TVillion::TvInfo

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
    @shows.each do |show|
      download = Download.where(show_id: show.id).order("season desc, episode desc").first
      unless download.nil?
        show.current_download = download
      end
    end
    @shows.sort!

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shows }
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = Show.find(params[:id])
    @downloads = Download.where(show_id: params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/new
  # GET /shows/new.json
  def new
    @show = Show.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(params[:show])

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render json: @show, status: :created, location: @show }
      else
        format.html { render action: "new" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shows/1
  # PUT /shows/1.json
  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update_attributes(params[:show])
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url }
      format.json { head :no_content }
    end
  end

  # GET /shows/search.json
  def search
    if params.include?(:query)
      @search_result = search_show(params[:query])
      puts @search_result
    end
    
    respond_to do |format|
      format.js
      format.html
      format.json { render json: @search_result }
    end
  end

  # GET /shows/1/downloads.json
  def downloads
    @downloads = Download.where(show_id: params[:id])
    
    respond_to do |format|
      format.json { render json: @downloads }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p><%= link_to "Shows", shows_path %></p>
<p><%= link_to "Jobs", :controller => "jobs" %></p>

app/views/jobs/get_tvinfo.html.erb
<h1>Jobs#get_tvinfo</h1>
<p>Status: <%= @status.result %></p>

app/views/jobs/index.html.erb
<h1>Run Job</h1>

<p><%= link_to 'Get TV Info', :action => "get_tvinfo" %></p>
<p><%= link_to 'Schedule Next Download', :action => "schedule_next_download" %></p>

app/views/jobs/schedule_next_download.html.erb
<h1>Jobs#schedule_next_download</h1>
<p>Status: <%= @status.result %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TVillion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :hd %><br />
    <%= f.radio_button :hd, true %>on
    <%= f.radio_button :hd, false %>off<br />
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.number_field :season %>
  </div>
  <div class="field">
    <%= f.label :episode %><br />
    <%= f.number_field :episode %>
  </div>
  <div class="field">
    <%= f.label :tvrage_id %><br />
    <%= f.number_field :tvrage_id %>
  </div>
  <div class="field">
    <%= f.label :search_name %><br />
    <%= f.text_field :search_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/_search_result.html.erb
<% unless @search_result.nil? %>
  <% @search_result.each_with_index do |result, index| %>
    <tr>
      <td class="id"><%= result[0] %></td>
      <td class="name"><%= result[1] %></td>
    </tr>
  <% end %>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<h1>Listing shows</h1>

<table width="100%" class="tablesorter" id="shows_main_table">
  <thead>
  <tr width="100%">
    <th>Status</th>
    <th>Name</th>
    <th>Season</th>
    <th>Episode</th>
    <th>Runtime</th>
    <th>HD</th>
    <th>Last Show Date</th>
    <th>Last Season</th>
    <th>Last Episode</th>
    <th>Next Show Date</th>
    <th>Next Season</th>
    <th>Next Episode</th>
    <th>Download</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  
  <tbody>
<% @shows.each_with_index do |show, index| %>
  <tr>
    <td><%= show.future_download? ? 'D' : '' %></td>
    <td><%= show.name %></td>
    <td><%= show.season %></td>
    <td><%= show.episode %></td>
    <td><%= show.runtime %></td>
    <td><%= show.hd %></td>
    <td><%= show.last_show_date %></td>
    <td><%= show.last_season %></td>
    <td><%= show.last_episode %></td>
    <td><%= show.next_show_date %></td>
    <td><%= show.next_season %></td>
    <td><%= show.next_episode %></td>
    <td><%= unless show.current_download.nil?
      '[%s,%s] %.0f%' % [show.current_download.season, show.current_download.episode, show.current_download.progressPercent]
    end %></td>
    <td><%= link_to 'Show', show %></td>
    <td><%= link_to 'Edit', edit_show_path(show) %></td>
    <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Show', search_shows_path %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/search.html.erb
<h1>Search and add show</h1>

<%= form_tag search_shows_path, :method => 'get', :remote => true, :id => "shows_search_lookup_form" do %>
  <div>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", :name => nil %>
  </div>
<% end %>

<div id="search_results">
  <table id="search_result_table" class="tablesorter">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

<div id="loading-indicator"><%= image_tag("ajax-loader.gif") %></div>
<div id="notice"></div>
<br/>
<div><%= link_to 'Back', shows_path %></div>

app/views/shows/search.js.erb
$('#search_result_table tbody').html('<%= escape_javascript(render("search_result")) %>');
$('#search_result_table').trigger('update');

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<img src="<%= @show.image_url %>" alt="<%= @show.image_url %>"/>
<p>
  <b>Name:</b>
  <%= @show.name %>
</p>
<p>
  <b>TVRage Id:</b>
  <%= @show.tvrage_id %>
</p>
<p>
  <b>Season:</b>
  <%= @show.season %>
</p>
<p>
  <b>Episode:</b>
  <%= @show.episode %>
</p>
<p>
  <b>Runtime:</b>
  <%= @show.runtime %>
</p>
<p>
  <b>HD:</b>
  <%= @show.hd %>
</p>
<p>
  <b>Last Show Date:</b>
  <%= @show.last_show_date %>
</p>
<p>
  <b>Last Season:</b>
  <%= @show.last_season %>
</p>
<p>
  <b>Last Episode:</b>
  <%= @show.last_episode %>
</p>
<p>
  <b>Next Show Date:</b>
  <%= @show.next_show_date %>
</p>
<p>
  <b>Next Season:</b>
  <%= @show.next_season %>
</p>
<p>
  <b>Next Episode:</b>
  <%= @show.next_episode %>
</p>
<p>
  <b>Search Name:</b>
  <%= @show.search_name %>
</p>
<% unless @downloads.nil? %>
<p>
  <b>Downloads:</b>
  <table width="100%" class="tablesorter" id="downloads_table">
    <thead>
    <tr>
      <th>Season</th>
      <th>Episode</th>
      <th>Transmission ID</th>
      <th>Status</th>
      <th>Progress</th>
    </tr>
    </thead>
  <% @downloads.each do |download| %>
    <tbody>
    <tr>
      <td><%= download.season %></td>
      <td><%= download.episode %></td>
      <td><%= download.download_id %></td>
      <td><%= download.statusName %></td>
      <td><div class="progressbar" percent="<%= download.progressPercent %>"><div class="progress-label"><%= download.progressPercent %></div></div></td>
    </tr>
    </tbody>
  <% end %>
  </table>
</p>
<% end %>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>